<?php

use Restserver\Libraries\REST_Controller;

defined('BASEPATH') or exit('No direct script access allowed');

// require APPPATH . 'libraries/REST_Controller.php';
// require APPPATH . 'libraries/Format.php';


class EstInspeksi extends REST_Controller
{

	public function __construct()
	{
		parent::__construct();
		date_default_timezone_set("Asia/Jakarta");
		$this->load->model('EstInspeksiModel');
		// $this->load->model('NotificationModel');
	}

	public function index_get()
	{ //Request Method select ALL

		$date = $this->get('tanggal');		//Get berdasarkan ID atau bisa juga FK

		$absen = $this->EstInspeksiModel->getInspeksi($date);


		if ($absen) {
			$this->set_response(
				$absen,
				REST_Controller::HTTP_OK
			);
		} else {
			$this->set_response([
				'status' => false,
				'message' => 'Absen Tidak Tersedia',
			], REST_Controller::HTTP_NOT_FOUND);
		}
	}

	public function index_post()
	{
		// $this->some_model->update_user( ... );
		$data = $this->post();
		// $this->set_response(array('data'=>$data), REST_Controller::HTTP_CREATED); 
		// return;
		$res = $this->EstInspeksiModel->Create($data);
		$message = array();
		if ($res) {

			$message = [
				'id' => $res, // Automatically generated by the model
				'message' => 'OK'
			];
		} else {
			$message = [
				'id' => null, // Automatically generated by the model
				'message' => 'NOT OK'
			];
		}


		$this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
	}
	public function UpdateStatus_post()
	{
		// $this->some_model->update_user( ... );
		$data = $this->post();
		// $this->set_response(array('data'=>$data), REST_Controller::HTTP_CREATED); 
		// return;
		$res = $this->EstInspeksiModel->updateStatus($data);
		$message = array();
		if ($res) {
			$message = [
				'id' => $res, // Automatically generated by the model
				'status' => 'OK'
			];
		} else {
			$message = [
				'id' => null, // Automatically generated by the model
				'status' => 'NOT OK'
			];
		}


		$this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
	}
	public function UploadFoto_post()
	{
		// $postData = $this->post();
		// $returndata = array('status' => 0, 'data' => $postData, 'message' => 'image upload failed');
		// 	$this->set_response($returndata, 200);
		// 	return;
		// echo   $_SERVER['DOCUMENT_ROOT'] . "/Demo/userfiles/absensi";
		$config = array(
			'upload_path' => $_SERVER['DOCUMENT_ROOT'] . "/"  . 'hcis_folder' . '/userfiles/inspeksi',	            //path for upload
			'allowed_types' => "gif|jpg|png|jpeg",   //restrict extension
			// 'max_size' => '100',
			// 'max_width' => '1024',
			// 'max_height' => '768',
			//'file_name' => 'logo_' . date('ymdhis')
		);
		$this->load->library('upload', $config);

		if ($this->upload->do_upload('file')) {
			$data = array('upload_data' => $this->upload->data());
			//$path = $config['upload_path'] . '/' . $data['upload_data']['orig_name'];
			// Write query to store image details of login user { }
			$returndata = array('status' => 1, 'data' => 'OK', 'message' => 'image uploaded successfully');
			$this->set_response($returndata, 200);
		} else {
			$error = array('error' => $this->upload->display_errors());
			$returndata = array('status' => 0, 'data' => $error, 'message' => 'image upload failed');
			$this->set_response($returndata, 200);
		}
	}
	public function getInspeksiByTanggal_post()
	{ //Request Method select ALL

		$tanggal1 = $this->post('tanggal_mulai');
		$tanggal2 = $this->post('tanggal_sd');


		$query = "select * from est_inspeksi where tanggal between '" . $tanggal1 . "' and '" . $tanggal2 . "'";

		$res = $this->db->query($query)->result_array();



		$this->set_response(array("status" => "OK", "data" => $res), REST_Controller::HTTP_OK);
	}
	function get_path_image($img = '', $size = '')
	{
		if (empty($size)) {
			return  $_SERVER['DOCUMENT_ROOT'] . "/"  . 'hcis_folder' . '/userfiles/inspeksi/' . $img;
		} else {
			$pisah = explode('.', $img);
			$ext = end($pisah);
			$nama_file = $pisah[0];

			return  $_SERVER['DOCUMENT_ROOT'] . "/"  . 'hcis_folder' . '/userfiles/inspeksi/' . $nama_file . '_' . $size . '.' . $ext;
		}
	}
	public function sendNotification($token, $title, $message, $payload)
	{
		// $token = $token;
		// $message = "Test notification message";
		$payload = array("click_action" => "FLUTTER_NOTIFICATION_CLICK");
		$this->load->library('fcm');
		$this->fcm->setTitle($title);
		$this->fcm->setMessage($message);

		/**
		 * set to true if the notificaton is used to invoke a function
		 * in the background
		 */
		$this->fcm->setIsBackground(false);

		/**
		 * payload is userd to send additional data in the notification
		 * This is purticularly useful for invoking functions in background
		 * -----------------------------------------------------------------
		 * set payload as null if no custom data is passing in the notification
		 */
		//$payload = array('notification' => '');
		$this->fcm->setPayload($payload);

		/**
		 * Send images in the notification
		 */
		$this->fcm->setImage('http://192.168.1.5/thermosigma-api-v2/assets/images/thermo.png');

		/**
		 * Get the compiled notification data as an array
		 */
		$json = $this->fcm->getPush();

		$p = $this->fcm->send($token, $json);

		// print_r($p);
	}
}
