<?php

use Restserver\Libraries\REST_Controller;

defined('BASEPATH') or exit('No direct script access allowed');

// require APPPATH . 'libraries/REST_Controller.php';
// require APPPATH . 'libraries/Format.php';


class HrmsAbsensiScan extends REST_Controller
{

	public function __construct()
	{
		parent::__construct();
		date_default_timezone_set("Asia/Jakarta");
		$this->load->model('HrmsAbsensiScanModel');
		// $this->load->model('NotificationModel');
	}

	public function index_get()
	{ //Request Method select ALL
		
		$date = $this->get('tanggal');	
		$karyawan_id = $this->get('karyawan_id');		//Get berdasarkan ID atau bisa juga FK

		$absen = $this->HrmsAbsensiScanModel->getAbsensi( $date,$karyawan_id);


		if ($absen) {
			$this->set_response(
				$absen,
				REST_Controller::HTTP_OK
			);
		} else {
			$this->set_response([
				'status' => false,
				'message' => 'Absen Tidak Tersedia',
			], REST_Controller::HTTP_NOT_FOUND);
		}
	}
	public function getAbsensi_post()
	{ //Request Method select ALL
		
		$tanggal = $this->post('tanggal');	

		
				$query = "select T1.karyawan_id ,nip,nama,T1.tanggal,Masuk.jam_masuk,Keluar.jam_keluar,Masuk.file_masuk,Masuk.location_masuk,Keluar.file_keluar,
				Keluar.location_keluar
				from(
				SELECT karyawan_id,nama,tanggal,nip
				 FROM payroll_absensi_scan inner join karyawan on payroll_absensi_scan.karyawan_id=karyawan.id
				 where  tanggal ='".$tanggal."'
				group by karyawan_id,tanggal,nama,nip)T1
				left join (SELECT karyawan_id,tanggal,time as jam_masuk,file as file_masuk,location as location_masuk FROM payroll_absensi_scan where status=0)as Masuk on T1.karyawan_id=Masuk.karyawan_id and T1.tanggal=Masuk.tanggal
				left join (SELECT karyawan_id,tanggal,time as jam_keluar,file as file_keluar,Location as location_keluar FROM payroll_absensi_scan where status=1)as Keluar on T1.karyawan_id=Keluar.karyawan_id and T1.tanggal=Keluar.tanggal ";

				$res = $this->db->query($query)->result_array();
				
		

				$this->set_response(array("status" => "OK", "data" => $res), REST_Controller::HTTP_OK);
	}
	public function index_post()
	{
		// $this->some_model->update_user( ... );
		$data = $this->post();
		// $this->set_response(array('data'=>$data), REST_Controller::HTTP_CREATED); 
		// return;
		$res = $this->HrmsAbsensiScanModel->Create($data);
		$message = array();
		if ($res) {
			// $ortu = $this->SiswaModel->getOrtu($data['siswa']);
			// foreach ($ortu as $key => $dat) {
			// 	$token = $dat['fcm_token'];
			// 	$namaSiswa = $dat['nama_siswa'];
			// 	$status = ($data['status']=="0")?"Masuk":"Pulang";
			// 	$Info = 'Hallo, ' . $dat['nama'] . '!  ';
			// 	$payload = array('notification' => '');
			// 	$this->sendNotification($token, $Info,  $namaSiswa . " telah melakukan Absensi ".$status. ' Pada: ' . $data['date'] . ' ' . $data['time'], $payload);
			// 	$login=$this->LoginModel->getLoginOrtu( $dat['id']);
			// 	$this->NotificationModel->createNotification('4', $Info. $namaSiswa . " telah melakukan Absensi ".$status. ' Pada: ' . $data['date'] . ' ' . $data['time'], $login['id'],'');

			// }
			$message = [
				'id' => $res, // Automatically generated by the model
				'message' => 'OK'
			];
		} else {
			$message = [
				'id' => null, // Automatically generated by the model
				'message' => 'NOT OK'
			];
		}


		$this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
	}
	public function UploadFoto_post()
	{
		// $postData = $this->post();
		// $returndata = array('status' => 0, 'data' => $postData, 'message' => 'image upload failed');
		// 	$this->set_response($returndata, 200);
		// 	return;
		// echo   $_SERVER['DOCUMENT_ROOT'] . "/Demo/userfiles/absensi";
		$config = array(
			'upload_path' => $_SERVER['DOCUMENT_ROOT'] . "/"  . 'hcis_folder' . '/userfiles/absensiQRCode',	            //path for upload
			'allowed_types' => "gif|jpg|png|jpeg",   //restrict extension
			// 'max_size' => '100',
			// 'max_width' => '1024',
			// 'max_height' => '768',
			//'file_name' => 'logo_' . date('ymdhis')
		);
		$this->load->library('upload', $config);

		if ($this->upload->do_upload('file')) {
			$data = array('upload_data' => $this->upload->data());
			//$path = $config['upload_path'] . '/' . $data['upload_data']['orig_name'];
			// Write query to store image details of login user { }
			$returndata = array('status' => 1, 'data' => 'OK', 'message' => 'image uploaded successfully');
			$this->set_response($returndata, 200);
		} else {
			$error = array('error' => $this->upload->display_errors());
			$returndata = array('status' => 0, 'data' => $error, 'message' => 'image upload failed');
			$this->set_response($returndata, 200);
		}
	}
	public function UploadFotoAndUpdate_post($idAbsensi)
	{
		// $postData = $this->post();
		// $returndata = array('status' => 0, 'data' => $postData, 'message' => 'image upload failed');
		// 	$this->set_response($returndata, 200);
		// 	return;
		// echo   $_SERVER['DOCUMENT_ROOT'] . "/Demo/userfiles/absensi";
		$config = array(
			'upload_path' => $_SERVER['DOCUMENT_ROOT'] . "/"  . 'hcis_folder' . '/userfiles/absensiQRCode',	            //path for upload
			'allowed_types' => "gif|jpg|png|jpeg",   //restrict extension
			// 'max_size' => '100',
			// 'max_width' => '1024',
			// 'max_height' => '768',
			//'file_name' => 'logo_' . date('ymdhis')
		);
		$this->load->library('upload', $config);

		if ($this->upload->do_upload('file')) {
			$data = array('upload_data' => $this->upload->data());
			//$path = $config['upload_path'] . '/' . $data['upload_data']['orig_name'];
			$this->db->where("id",$idAbsensi);
			$this->db->update("payroll_absensi_scan", array(
				'file' =>$data['upload_data']['file_name'],
					
			));
			$returndata = array('status' => 1, 'data' => 'OK', 'message' => 'image uploaded successfully');
			$this->set_response($returndata, 200);
		} else {
			$error = array('error' => $this->upload->display_errors());
			$returndata = array('status' => 0, 'data' => $error, 'message' => 'image upload failed');
			$this->set_response($returndata, 200);
		}
	}
	function get_path_image($img = '', $size = '')
	{
		if (empty($size)) {
			return  $_SERVER['DOCUMENT_ROOT'] . "/"  . 'hcis_folder' . '/userfiles/absensiQRCode/' . $img;
		} else {
			$pisah = explode('.', $img);
			$ext = end($pisah);
			$nama_file = $pisah[0];

			return  $_SERVER['DOCUMENT_ROOT'] . "/"  . 'hcis_folder' . '/userfiles/inspeksi/' . $nama_file . '_' . $size . '.' . $ext;
		}
	}
	public function sendNotification($token, $title, $message, $payload)
	{
		// $token = $token;
		// $message = "Test notification message";
		$payload = array("click_action" => "FLUTTER_NOTIFICATION_CLICK");
		$this->load->library('fcm');
		$this->fcm->setTitle($title);
		$this->fcm->setMessage($message);

		/**
		 * set to true if the notificaton is used to invoke a function
		 * in the background
		 */
		$this->fcm->setIsBackground(false);

		/**
		 * payload is userd to send additional data in the notification
		 * This is purticularly useful for invoking functions in background
		 * -----------------------------------------------------------------
		 * set payload as null if no custom data is passing in the notification
		 */
		//$payload = array('notification' => '');
		$this->fcm->setPayload($payload);

		/**
		 * Send images in the notification
		 */
		$this->fcm->setImage(base_url('logo_antech.png'));

		/**
		 * Get the compiled notification data as an array
		 */
		$json = $this->fcm->getPush();

		$p = $this->fcm->send($token, $json);

		// print_r($p);
	}
}
